exports.resources = [
  { name: 'Pod' },
  { name: 'ReplicaSet' },
  { name: 'Deployment' },
  { name: 'Ingress' },
  { name: 'Service' },
];

exports.resourceList = exports.resources.map((resource) => {
  return resource.name;
});

exports.questionList = [
  {
    type: 'list',
    name: 'resourceType',
    message: 'Resource Type:',
    choices: this.resourceList,
  },
  {
    type: 'chalk-pipe',
    name: 'name',
    message: 'Name:',
    default: 'canary-test',
  },
  {
    type: 'chalk-pipe',
    name: 'namespace',
    message: 'Namespace:',
    default: 'default',
  },
  {
    type: 'chalk-pipe',
    name: 'labels',
    message: 'Labels:',
    default: 'key=value',
  },
];

exports.officialDockerImages = [
  'couchbase',
  'postgres',
  'traefik',
  'ubuntu',
  'redis',
  'node',
  'mongo',
  'mysql',
  'mariadb',
  'nginx',
  'httpd',
  'registry',
  'golang',
  'aerospike',
  'openjdk',
  'memcached',
  'python',
  'docker',
  'consul',
  'debian',
  'rabbitmq',
  'wordpress',
  'centos',
  'influxdb',
  'haproxy',
  'nextcloud',
  'ruby',
  'elasticsearch',
  'maven',
  'php',
  'tomcat',
  'sonarqube',
  'crate',
  'amazonlinux',
  'telegraf',
  'eclipse-mosquitto',
  'logstash',
  'gradle',
  'kibana',
  'cassandra',
  'jenkins',
  'ghost',
  'couchdb',
  'solr',
  'vault',
  'bash',
  'perl',
  'chronograf',
  'buildpack-deps',
  'flink',
  'drupal',
  'zookeeper',
  'kong',
  'adminer',
  'swarm',
  'mongo-express',
  'nats',
  'rethinkdb',
  'joomla',
  'percona',
  'teamspeak',
  'kapacitor',
  'rocket.chat',
  'matomo',
  'groovy',
  'fedora',
  'nats-streaming',
  'owncloud',
  'composer',
  'jruby',
  'erlang',
  'mediawiki',
  'znc',
  'pypy',
  'redmine',
  'jetty',
  'xwiki',
  'elixir',
  'mono',
  'websphere-liberty',
  'tomee',
  'rust',
  'odoo',
  'oraclelinux',
  'iojs',
  'swift',
  'haxe',
  'arangodb',
  'ros',
  'clojure',
  'hylang',
  'piwik',
  'django',
  'orientdb',
  'opensuse',
  'ibmjava',
  'ubuntu-debootstrap',
  'neurodebian',
  'rails',
  'yourls',
  'julia',
  'notary',
  'irssi',
  'open-liberty',
  'cirros',
  'amazoncorretto',
  'plone',
  'photon',
  'backdrop',
  'kaazing-gateway',
  'haskell',
  'php-zendserver',
  'geonetwork',
  'r-base',
  'clearlinux',
  'gazebo',
  'bonita',
  'nuxeo',
  'convertigo',
  'storm',
  'lightstreamer',
  'celery',
  'thrift',
  'fluentd',
  'fsharp',
  'eggdrop',
  'caddy',
  'docker-dev',
  'swipl',
  'spiped',
  'rapidoid',
  'rakudo-star',
  'varnish',
  'postfixadmin',
  'express-gateway',
  'mageia',
  'glassfish',
  'archlinux',
  'silverpeas',
  'known',
  'crux',
  'sl',
  'sourcemage',
  'euleros',
  'clefos',
  'alt',
  'friendica',
  'hipache',
  'jobber',
  'sapmachine',
  'scratch',
  'cheers',
];
